### ISSUE TITLE
The Copy button in PRE blocks doesn't render correctly in all cases

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.github.io#174]
The Copy button on PRE sections is rendered inconsistenty. For example, on this page https://istio.io/docs/tasks/integrating-services-into-istio.html it is not as tall as on other pages.

**Comment by ldemailly** [comment]
Also (copying from previous issue:)
people are complaining about the \<copy\> button/link:

- [ ] it's transparent over text below which makes both the button and the text under it hard to read (should have some background)
- [ ] the examples often include the output of the command, which makes them un-pastable as is - we should ideally split the command from the output (would look nicer too) - maybe we could put $ in front of command and copy would copy only lines with a $ ?

**Comment by geeknoid** [comment]
I believe the second bullet has been addressed. All commands are now in separate blocks then their output.

**Comment by ldemailly** [comment]
going through the page I found another example not split that I fixed:
https://github.com/istio/istio.github.io/commit/515063218f859801bfbad691f1e81dc07f1c8c80

**Comment by davetropeano** [comment]
Two basic options to fix the where the copy button appears and it's size:

1. place above the `<code>` block
2. place to the side

Here's what the options look like. I prefer on top but that's just me. Thoughts?

![image](https://cloud.githubusercontent.com/assets/1832614/26128496/a02b8f4a-3a5a-11e7-9909-7330059eed11.png)

**Comment by geeknoid** [comment]
I actually experimented last week with rendering turning the Copy button by
90 degrees and putting it to the right of the PRE block. I couldn't quite
get the formatting to work right, but it seemed to be a reasonable
approach.

Anyway, putting it on top is fine and dandy.

Thanks.

**Comment by geeknoid** [comment]
Dav, the Copy button is still showing up with different heights for some reason.

If you go to istio.io/docs/tasks/installing-istio.html and scroll through the page, you can hover the mouse over the various Copy buttons and see they're different heights. This was the case previously and I couldn't figure out why...

**Comment by ldemailly** [comment]
it's not working anymore with chrome - click copy and:
```
Uncaught Error: Invalid "target" value, use a valid Element
    at a.set (clipboard.min.js:1)
    at a.resolveOptions (clipboard.min.js:1)
    at new a (clipboard.min.js:1)
    at b.onClick (clipboard.min.js:1)
    at HTMLBodyElement.<anonymous> (clipboard.min.js:1)
    at HTMLBodyElement.<anonymous> (clipboard.min.js:1)
```

**Comment by ldemailly** [comment]
"davetropeano was unassigned by ldemailly just now"  I didn't...

**Comment by ldemailly** [comment]
looks like the error is in a new task issue #248

**Comment by geeknoid** [comment]
The rendering problem I mentioned still exists (the Copy button has different height in different uses)

**Comment by ldemailly** [comment]
k and while we're at it if we can change the color - that bordeaux red / brown doesn't look great

**Comment by davetropeano** [comment]
Hmmm... I think something didn't get merged perhaps. The button is working for me and the CSS on the button isn't getting overriden from the fixed value I set. Looking again..

**Comment by davetropeano** [comment]
@geeknoid I submitted a PR to fix the processing of the button click - this one liner got lost in the merge set. Apologies. I cannot duplicate the sizing issue you are seeing. The button is fixed to 14px in the CSS -- it was previously set to 1 REM (a *relative* em) so that's why it was changing size. But every page I looked at and verified was 14 px... what URLs are you comparing to see this?
